# Generated by Django 5.0.2 on 2024-03-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemodel",
            name="Joine_date",
            field=models.DateTimeField(),
        ),
    ]
