# Generated by Django 5.0.2 on 2024-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_alter_employeemodel_joine_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemodel",
            name="DOB",
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employeemodel",
            name="Email",
            field=models.EmailField(max_length=100),
        ),
    ]
