# Generated by Django 5.0.2 on 2024-03-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_alter_employeemodel_dob_alter_employeemodel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemodel",
            name="Phone",
            field=models.IntegerField(),
        ),
    ]
