# Generated by Django 5.0.2 on 2024-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0004_alter_employeemodel_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemodel",
            name="DOB",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employeemodel",
            name="Email",
            field=models.EmailField(max_length=254),
        ),
    ]
